[project]
name = "pygame-template-renewed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "moderngl>=5.12.0",
    "multimethod>=2.0",
    "pygame-ce>=2.5.2",
]
